### ISSUE TITLE
gateway with no ROS_HOSTNAME or ROS_IP

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#126]
[INFO] [WallTime: 1355377302.854995] Gateway : registering a new node [listener_whoola_11539_579484006608799533] for [{gateway gateway1: {type: subscriber, name/regex: /chatter, node-name/regex: /listener}}]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "/home/jihoonl/ros/groovy/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/hub_api.py", line 123, in run
    self._remote_gateway_request_callbacks['flip'](registration)
  File "/home/jihoonl/ros/groovy/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_sync.py", line 489, in process_remote_gateway_flip_request
    new_registration = self.master.register(registration)
  File "/home/jihoonl/ros/groovy/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 73, in register
    xmlrpcapi(registration.connection.xmlrpc_uri).publisherUpdate('/master', registration.connection.rule.name, pub_uri_list)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

**Comment by stonier** [comment]
Implement some error handling here.

**Comment by stonier** [comment]
Groundwork done in 863ceb40d80c2c42aaa36ea275eb413ae858ae7c
