### ISSUE TITLE
When remote node is being killed...

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#128]
It kills gateway thread

---

[INFO] [WallTime: 1355404557.005741] Gateway : received an unflip request from gateway donizetti: {type: subscriber, name/regex: /test_robot/kitchen/command, node-name/regex: /kitchen}
[INFO] [WallTime: 1355404557.006157] Gateway : unregistering local node [kitchen_whoola_25606_8742800302169353151] for [{gateway donizetti: {type: subscriber, name/regex: /test_robot/kitchen/command, node-name/regex: /kitchen}}]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "/home/jihoonl/ros/groovy/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/hub_api.py", line 125, in run
    self._remote_gateway_request_callbacks['unflip'](utils.get_rule_from_list%28contents%29, source)
  File "/home/jihoonl/ros/groovy/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_sync.py", line 497, in process_remote_gateway_unflip_request
    self.master.unregister(existing_registration)
  File "/home/jihoonl/ros/groovy/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 119, in unregister
    xmlrpcapi(registration.connection.xmlrpc_uri).publisherUpdate('/master', registration.connection.rule.name, [])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

---

**Comment by stonier** [comment]
I had wondered how you were getting this...fixed in ce0fe5e75a939163ba15a297640d315df6594bc8
