### ISSUE TITLE
Failure when hub is not available.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#138]
Tried to start concert_client when concert_master is not up. 

[INFO] [WallTime: 1364263198.164210] Gateway : looking to see if zeroconf services are available...
[INFO] [WallTime: 1364263198.265161] App Manager : loading apps file [/home/jihoonl/research/ros/hydro/turtlebot/src/rocon/rocon_demos/drink_delivery/cafe_database/rapps/cafe_database.rapps]
[INFO] [WallTime: 1364263198.375554] App Manager : loading app 'cafe_database/cafe_database'
[INFO] [WallTime: 1364263199.173927] Gateway : discovered hub zeroconf service at localhost:6380
[INFO] [WallTime: 1364263199.174875] Gateway : resolved hub name [None].
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/hydro/turtlebot/src/rocon/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/jihoonl/research/ros/hydro/turtlebot/src/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 53, in spin
    self._scan_for_zeroconf_hubs(previously_found_hubs)
  File "/home/jihoonl/research/ros/hydro/turtlebot/src/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 188, in _scan_for_zeroconf_hubs
    connect_result = self._connect(ip,port)
  File "/home/jihoonl/research/ros/hydro/turtlebot/src/rocon/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 209, in _connect
    if (len(self.param['hub_whitelist']) == 0) or (ip in self.param['hub_whitelist']) or (hub_name in self.param['hub_whitelist']):
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by stonier** [comment]
There were timing problems in the discovery sequence. This one looks like the race condition that occurs inbetween the redis server being up and the key being installed on the server.

That's been fixed in multi-hub.
