### ISSUE TITLE
gateway does not die properly when it terminates

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#150]
```
jihoonl@whoola:~/research/ros/hydro/rocon/debug/src/rocon_demos/multirobot_control/multinav_database/launch$ roslaunch multinav_database_client.launch ... logging to /home/jihoonl/.ros/log/63d90f26-a590-11e2-b203-3085a9948f5e/roslaunch-whoola-28529.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://whoola:48116/

SUMMARY
========

PARAMETERS
 * /appmanager/app_lists
 * /appmanager/app_store_url
 * /appmanager/remote_controller_blacklist
 * /appmanager/remote_controller_whitelist
 * /appmanager/robot_name
 * /appmanager/robot_type
 * /gateway/default_blacklist
 * /gateway/firewall
 * /gateway/hub_whitelist
 * /gateway/name
 * /gateway/watch_loop_period
 * /rosdistro
 * /rosversion

NODES
  /zeroconf/
    zeroconf (zeroconf_avahi/zeroconf)
  /
    appmanager (rocon_app_manager/rapp_manager.py)
    gateway (rocon_gateway/gateway.py)

auto-starting new master
process[master]: started with pid [28543]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 63d90f26-a590-11e2-b203-3085a9948f5e
process[rosout-1]: started with pid [28556]
started core service [/rosout]
process[zeroconf/zeroconf-2]: started with pid [28568]
process[gateway-3]: started with pid [28589]
process[appmanager-4]: started with pid [28596]
[INFO] [WallTime: 1366005035.694779] App Manager : loading apps file [/home/jihoonl/research/ros/hydro/rocon/debug/src/rocon_demos/multirobot_control/multinav_database/rapps/shared_database.rapps]
[INFO] [WallTime: 1366005035.813370] App Manager : loading app 'multinav_database/map_sharing'
[INFO] [WallTime: 1366005036.017170] App Manager : advertising services
^C[appmanager-4] killing on exit
 [gateway-3] killing on exit
[zeroconf/zeroconf-2] killing on exit
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/hydro/rocon/debug/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/jihoonl/research/ros/hydro/rocon/debug/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 54, in spin
    self._scan_for_zeroconf_hubs(previously_found_hubs)
  File "/home/jihoonl/research/ros/hydro/rocon/debug/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 185, in _scan_for_zeroconf_hubs
    resp = self._zeroconf_services["list_discovered_services"](req)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 436, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 496, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 464, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
rospy.service.ServiceException: service [/zeroconf/list_discovered_services] unavailable
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by stonier** [comment]
Known problem when you terminate before giving the chance for a gateway to connect to a hub.

The startup sequence in multihub is much different so this problem will no longer be there (can't guarantee there won't be other new and exciting issues though!).
