### ISSUE TITLE
Multiple launchers on a single port

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#151]
Can't currently do this with `rocon_test` (`rocon_launch` can). e.g.

```
<concert>
  <launch package="rocon_gateway_tests" name="multihub_gateway.xml" port="11311"/>
  <launch package="rocon_gateway_tests" name="tutorials.xml" port="11311"/>
  <launch package="rocon_gateway_tests" name="advertise_all.xml" port="11311"/>
  <launch package="rocon_gateway_tests" name="primary_hub.xml" port="11312"/>
  <launch package="rocon_gateway_tests" name="secondary_hub.xml" port="11313"/>
  <launch package="rocon_gateway_tests" name="undiscovered_hub.xml" port="11314"/>
  <launch package="rocon_gateway_tests" name="test_pulls.xml" port="11315"/>
</concert>
```

fails with error message:

```
ERROR: run_id on parameter server does not match declared run_id: 9e9da290-a59d-11e2-8718-6cf049781259 vs 9f064eb2-a59d-11e2-8718-6cf049781259
  File "/usr/lib/python2.7/unittest/case.py", line 318, in run
    self.setUp()
  File "/opt/rocon/src/rocon_multimaster/rocon_test/src/rocon_test/runner.py", line 120, in setUp
    rocon_launch_configuration.parent.start()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self.runner.launch()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 644, in launch
    self._setup()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 620, in _setup
    self._launch_master()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 409, in _launch_master
    self._check_and_set_run_id(param_server, self.run_id)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/launch.py", line 440, in _check_and_set_run_id
    raise RLException("run_id on parameter server does not match declared run_id: %s vs %s"%(val, run_id))
--------------------------------------------------------------------------------
[zeroconf/zeroconf-2] killing on exit
 [gateway-3] killing on exit
Traceback (most recent call last):
  File "/opt/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 20, in <module>
    rospy.init_node('gateway')
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/client.py", line 317, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete
[rosout-1] killing on exit
[master] killing on exit
[ROSTEST]-----------------------------------------------------------------------

```

**Comment by stonier** [comment]
Maybe something to do with the fact that we don't want to start another parent?

**Comment by stonier** [comment]
Ah, maybe this is where roslaunch uses the idea of children.

Nope - a second roslauncher on the same port is also a parent.
