### ISSUE TITLE
Hub crashes when stored configuration present

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#166]
```
error 1: hub is dead


started roslaunch server http://192.168.10.131:56007/

SUMMARY
========

PARAMETERS
 * /concert/conductor/auto_invite
 * /concert/gateway/default_blacklist
 * /concert/gateway/firewall
 * /concert/gateway/hub_uri
 * /concert/gateway/hub_whitelist
 * /concert/gateway/name
 * /concert/gateway/watch_loop_period
 * /concert/gateway_hub/max_memory
 * /concert/gateway_hub/name
 * /concert/gateway_hub/port
 * /concert/gateway_hub/zeroconf
 * /concert/orchestration/actions
 * /concert/orchestration/auto_start
 * /concert/orchestration/edges
 * /concert/orchestration/name
 * /concert/orchestration/nodes
 * /concert/orchestration/topics
 * /rosbridge/port
 * /rosbridge_websocket/authenticate
 * /rosdistro
 * /rosversion

NODES
  /concert/zeroconf/
    zeroconf (zeroconf_avahi/zeroconf)
  /
    map_relay_service (map_service/map_service_relay.py)
    rosapi (rosapi/rosapi)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)
  /concert/
    conductor (concert_conductor/conductor.py)
    gateway (rocon_gateway/gateway.py)
    gateway_hub (rocon_hub/hub.py)
    orchestration (concert_orchestra/orchestra.py)
    rocon_tf_reconstructor (rocon_tf_reconstructor/rocon_tf_reconstructor)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [2317]
ROS_MASTER_URI=http://192.168.10.131:11311/

setting /run_id to ba2928f0-d7e2-11e2-ab49-207c8f21b358
process[rosout-1]: started with pid [2387]
started core service [/rosout]
process[concert/gateway_hub-2]: started with pid [2442]
process[concert/zeroconf/zeroconf-3]: started with pid [2493]
Traceback (most recent call last):
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_hub/scripts/hub.py", line 11, in <module>
    rocon_hub.main()
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_hub/src/rocon_hub/main.py", line 38, in main
    redi = redis_server.RedisServer(param)
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_hub/src/rocon_hub/redis_server.py", line 44, in __init__
    self._setup()
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_hub/src/rocon_hub/redis_server.py", line 52, in _setup
    shutil.rmtree(self._home_dir)
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/yujin/.ros/redis/cafe_concert'
[concert/gateway_hub-2] process has died [pid 2442, exit code 1, cmd /home/yujin/cafe_concert/src/rocon_multimaster/rocon_hub/scripts/hub.py __name:=gateway_hub __log:=/home/yujin/.ros/log/ba2928f0-d7e2-11e2-ab49-207c8f21b358/concert-gateway_hub-2.log].
log file: /home/yujin/.ros/log/ba2928f0-d7e2-11e2-ab49-207c8f21b358/concert-gateway_hub-2*.log
process[concert/gateway-4]: started with pid [2574]
process[concert/conductor-5]: started with pid [2704]
[INFO] [WallTime: 1371537964.128777] Gateway : generated unique hash name [cafe_concert0f2894713dd2447987e62b0b354840a2]
[INFO] [WallTime: 1371537964.157116] Gateway : checking if zeroconf services are available...
[ INFO] [1371537964.167000360]: Zeroconf: added a listener [_ros-multimaster-hub._tcp]
process[concert/orchestration-6]: started with pid [2783]
process[concert/rocon_tf_reconstructor-7]: started with pid [2831]
[ INFO] [1371537965.861409717]: Initialized
[ INFO] [1371537965.861542711]: In Spin!
[INFO] [WallTime: 1371537965.867767] Orchestration : initialised the implementation server.
process[concert/rviz-8]: started with pid [2871]
[ INFO] [1371537966.992957056]: rviz version 1.9.28
[ INFO] [1371537966.993181558]: compiled against OGRE version 1.7.4 (Cthugha)
process[map_relay_service-9]: started with pid [2889]
process[rosbridge_websocket-10]: started with pid [2900]
[INFO] [WallTime: 1371537968.531377] Initialized
process[rosapi-11]: started with pid [2930]
[INFO] [WallTime: 1371537969.467728] Rosbridge WebSocket server started on port 9090
[ INFO] [1371537970.653242317]: OpenGl version: 3.3 (GLSL 3.3).
[INFO] [WallTime: 1371537971.693353] Rosapi started
[concert/rviz-8] process has finished cleanly
log file: /home/yujin/.ros/log/ba2928f0-d7e2-11e2-ab49-207c8f21b358/concert-rviz-8*.log


```

**Comment by stonier** [comment]
Maybe the hub script should clean this up before starting...I just got a similar one:

```
Directory not empty: '/home/yujin/.ros/redis/primary_hub
```
