### ISSUE TITLE
unflip request unexpected traceback

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#167]
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 68, in run
    self._remote_gateway_request_callbacks['unflip'](utils.get_rule_from_list(contents), source)
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 266, in process_remote_gateway_unflip_request
    self.master.unregister(existing_registration)
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 366, in unregister
    self._unregister_subscriber(node_master, registration.connection.xmlrpc_uri, registration.connection.rule.name)
  File "/home/yujin/cafe_concert/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 424, in _unregister_subscriber
    xmlrpcapi(xmlrpc_uri).publisherUpdate('/master', name, [])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault -1: 'publisherUpdate: unknown method name'>

```

**Comment by stonier** [comment]
The unregister subscriber has two steps:
- Inform the subscriber node of publisher update (empty list)
- Unregister with the master locally

Note the first step is filling in to do the master's job of usually informing the subscriber when there are connections broken (in this case, the remote subscriber with remote publishers). Refer to #125 for more detail.

The fix is just to catch and ignore the fault, since if the subscriber is going down, it doesn't need to be updated!
