### ISSUE TITLE
watcher thread failure

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#198]
Just got this error in the hub sidekick (watcher thread):

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/piyushk/catkin_ws/src/rocon_multimaster/rocon_hub/src/rocon_hub/watcher.py", line 80, in run
    self.pingers[gateway] = Pinger(gateway_info.ip, self.gateway_ping_frequency, self.gateway_timeout)
AttributeError: 'NoneType' object has no attribute 'ip'
```

I suspect this happened because redis was being updated with the new gateway when the hub sidekick managed to ping it. We got the gateway name from gatewaylist, but the actual gateway information was not present. Fix should be trivial.

**Comment by stonier** [comment]
:neckbeard:
