### ISSUE TITLE
Registering service arguments sometimes None

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#201]
Trying chatter concert. 
Sometimes conductor side gateway crashes with this error.

```
[INFO] [WallTime: 1383099477.233836] Conductor: retrieving client information [dude]
[ERROR] [WallTime: 1383099477.392198] Gateway : tried to register a service with type_info set to None [/dude/platform_info, None, http://192.168.10.129:46394/]
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 74, in spin
    self.watcher_thread.start()
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 75, in start
    self._gateway.update_pulled_interface(connections, remote_gateway_hub_index)
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 196, in update_pulled_interface
    new_registration = self.master.register(registration)
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 342, in register
    node_master.registerService(registration.connection.rule.name, registration.connection.type_info, registration.connection.xmlrpc_uri)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 315, in registerService
    return self._succeed(self.handle.registerService(self.caller_id, service, service_api, caller_api))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1572, in __request
    allow_none=self.__allow_none)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1085, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 632, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 654, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 658, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled

```

**Comment by stonier** [comment]
Looks like this one, #173 raising its ugly head again. Reopening that one instead.
