### ISSUE TITLE
Watcher thread segmentation fault.

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#207]
I am receiving the following error in my simulated concert demo. I have merged in hydro-devel for rocon_msgs, rocon_app_platform, rocon_multimaster and rocon_concert.

The bug is present as of: https://github.com/robotics-in-concert/rocon_multimaster/commit/bb04cf35c74cba7fd17a6e105c1e6ca39a02ca05

```
Traceback (most recent call last):
  File "/home/piyushk/catkin_ws/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/piyushk/catkin_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 76, in spin
    self.watcher_thread.start()
  File "/home/piyushk/catkin_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 74, in start
    self._gateway.update_flipped_interface(connections, remote_gateway_hub_index)
  File "/home/piyushk/catkin_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 131, in update_flipped_interface
    connections = self.master.generate_connection_details(flip.rule.type, flip.rule.name, flip.rule.node)
  File "/home/piyushk/catkin_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 494, in generate_connection_details
    connections.append(utils.Connection(Rule(SUBSCRIBER, name + '/goal', node), type_info, xmlrpc_uri))
UnboundLocalError: local variable 'type_info' referenced before assignment
```

**Comment by stonier** [comment]
:+1:
