### ISSUE TITLE
Connection refused to redis server

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#212]
```
Traceback (most recent call last):
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 76, in spin
    self.watcher_thread.start()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 76, in start
    self._gateway.update_pulled_interface(connections, remote_gateway_hub_index)
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 176, in update_pulled_interface
    remote_connections[remote_gateway].update(hub.get_remote_connection_state(remote_gateway))
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 391, in get_remote_connection_state
    public_interface = self._redis_server.smembers(key)
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/client.py", line 919, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/client.py", line 349, in execute_command
    connection.send_command(*args)
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/connection.py", line 299, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/connection.py", line 281, in send_packed_command
    self.connect()
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/connection.py", line 229, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting 192.168.10.129:6380. Connection refused.
```

**Comment by stonier** [comment]
1d90ccbd

I think we have more - should do a search and destroy on all redis requests sometime.
