### ISSUE TITLE
Hub crashing when startup

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#216]
```
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_hub/scripts/hub.py", line 11, in <module>
    rocon_hub.main()
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_hub/src/rocon_hub/main.py", line 39, in main
    redi = redis_server.RedisServer(param)
  File "/home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_hub/src/rocon_hub/redis_server.py", line 40, in __init__
    shutil.rmtree(self._home_dir)
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/jihoonl/.ros/redis/concert_tutorial'
[concert/gateway_hub-7] process has died [pid 30189, exit code 1, cmd /home/jihoonl/research/ros/rocon/src/rocon_multimaster/rocon_hub/scripts/hub.py __name:=gateway_hub __log:=/home/jihoonl/.ros/log/76b19262-4d0b-11e3-9f39-3085a9948f5e/concert-gateway_hub-7.log].
log file: /home/jihoonl/.ros/log/76b19262-4d0b-11e3-9f39-3085a9948f5e/concert-gateway_hub-7*.log
```

**Comment by stonier** [comment]
This now has a check for the directory already, closing.
