### ISSUE TITLE
Multi-Concert Problems

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#217]
Robot started an app while two concerts("OPP Concert", "Concert Tutorial") are visible in the network.

"OPP concert" requested robot to start an app but the robot flipped the public interface into "Concert Tutorial"

For example, OPP Concert requested the robot to start android_teleop app. But the robot flipped cmd_vel and image topic to Concert Tutorial.

**Comment by jihoonl** [comment]
With empty ROBOT_HUB_WHITELIST

**Comment by stonier** [comment]
Changed the title of this to reflect multi-concert issues in general.

**Comment by stonier** [comment]
**Connections Up and Down**

Saw this error where 192.168.10.109 wasn't the local concert tutorial:

```
[INFO] [WallTime: 1385444705.382195] Gateway : discovered hub via zeroconf [192.168.10.109:6380]
[INFO] [WallTime: 1385444706.850807] Gateway : registering on the hub [Concert Tutorial]
[INFO] [WallTime: 1385444813.796861] Gateway : lost connection to the hub [Concert Tutorial][192.168.10.109:6380]
[ERROR] [WallTime: 1385444814.067830] Gateway: Unable to update network interface information
Traceback (most recent call last):
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 64, in spin
    self._gateway.spin()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 76, in spin
    self.watcher_thread.start()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 76, in start
    self._gateway.update_pulled_interface(connections, remote_gateway_hub_index)
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 176, in update_pulled_interface
    remote_connections[remote_gateway].update(hub.get_remote_connection_state(remote_gateway))
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 391, in get_remote_connection_state
    public_interface = self._redis_server.smembers(key)
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/client.py", line 919, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/client.py", line 349, in execute_command
    connection.send_command(*args)
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/connection.py", line 299, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/connection.py", line 281, in send_packed_command
    self.connect()
  File "/mnt/ros/rocon/src/rocon_multimaster/redis/src/redis/connection.py", line 229, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting 192.168.10.109:6380. Connection refused.
```

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_app_platform/issues/106

**Comment by stonier** [comment]
Above and this are duplicates. Still some remaining issues in notifying the concert. Following up on that in other issues though.
