### ISSUE TITLE
genpy.message.SerializationError: field remotes[].gateway must be of type str

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#225]
While concert and robot are running, I killed the concert master. Then robot's terminal showed this stacktrace 

```
Unhandled exception in thread started by <bound method RappManager._monitor_rapp of <rocon_app_manager.rapp_manager.RappManager object at 0x1eaf250>>
Traceback (most recent call last):
  File "/home/yujin/turtlebot/kobuki_test/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 414, in _monitor_rapp
    self._process_stop_app()
  File "/home/yujin/turtlebot/kobuki_test/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 394, in _process_stop_app
    self._flip_connections(self._remote_name, action_servers, gateway_msgs.ConnectionType.ACTION_SERVER, cancel_flag=True)
  File "/home/yujin/turtlebot/kobuki_test/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 469, in _flip_connections
    resp = self._gateway_services['flip'](req)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 605, in send_message
    serialize_message(self.write_buff, seq, msg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/home/yujin/turtlebot/kobuki_test/devel/lib/python2.7/dist-packages/gateway_msgs/srv/_Remote.py", line 133, in serialize
    except TypeError as te: self._check_types(te)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 311, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 233, in check_type
    check_type(field_name+"[]", base_type, v)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 243, in check_type
    check_type("%s.%s"%(field_name,n), t, getattr(field_val, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 209, in check_type
    raise SerializationError('field %s must be of type str'%field_name)
genpy.message.SerializationError: field remotes[].gateway must be of type str
```

**Comment by stonier** [comment]
Old issue...graveyarding until we see again.
