### ISSUE TITLE
gateways still cannot correctly detect when the hub goes down

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#228]
Scenario:
- Run a local gateway and remote gateway on 2 separate laptops. No connections needed.
- Use ROS_HOSTNAME instead of ROS_IP
- Resolve own hostname to 127.0.0.1 in /etc/hosts. Resolve other hostname to actual network address.

The point of the above experiment is that removing the network interface is similar to a network outage (the local system continues to function)

Successful:
- Turning the network interface off and back on the remote machine works correctly

Failure:
- Turning the network interface off on the local machine (the one with the hub) is quite bizzare. Local detects remote is gone. Remote never detects that local is gone, and on reestablishing connectivity crashes.

**Comment by piyushk** [comment]
Error is below. This error happens because RedisConnectionCheckerThread does not call connection lost hook. I suspect if we deactivate the hub and reactivate it, we'll be fine.

```
Traceback (most recent call last):
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 70, in spin
    self._gateway.spin()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 76, in spin
    self.watcher_thread.start()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 72, in start
    remote_gateway_hub_index = self._hub_manager.create_remote_gateway_hub_index()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/hub_manager.py", line 78, in create_remote_gateway_hub_index
    for remote_gateway in hub.list_remote_gateway_names():
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 401, in list_remote_gateway_names
    gateway_keys = self._redis_server.smembers(self._redis_keys['gatewaylist'])
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/client.py", line 919, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/client.py", line 346, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/client.py", line 356, in parse_response
    response = connection.read_response()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/connection.py", line 304, in read_response
    response = self._parser.read_response()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/connection.py", line 138, in read_response
    response = [self.read_response() for i in xrange(length)]
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/connection.py", line 102, in read_response
    response = self.read()
  File "/home/piyushk/rocon_ws/src/rocon_multimaster/redis/src/redis/connection.py", line 87, in read
    return self._fp.readline()[:-2]
AttributeError: 'NoneType' object has no attribute 'readline'
```

**Comment by piyushk** [comment]
Incorrect analysis last time around. I was able to produce the same error when switching off the network interface on the remote as well. There are 2 solutions to the problem:

1) @stonier I just noticed that at some point we stopped using rocon_hub_client.HubConnection. Was there a reason? IIRC, the socket timeout was preventing the error above. 
2) There is an alternate solution where redis socket needs to be shutdown before it can be closed. This issue has been fixed upstream, and at some point in time we could re-sync redis (or set it up in a complete third party manner). Since we obviously cannot re-sync redis right now, I can implement the one line solution in our copy of redis. I need to add this line: https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L300

Let me know what you think is best.

**Comment by piyushk** [comment]
I've fixed the crash. However remote still does not detect that local is gone. Need to figure out why.

**Comment by piyushk** [comment]
I've fixed this for now. I've also realized that we should be definitely use socket timeouts. I'll open a new issue on that, which can be fixed post-demo.

**Comment by stonier** [comment]
@piyushk Re 1) Im afraid I absolutely can't remember. Would have to dig up the contents of my brain to answer for you. Do you still need the information?

**Comment by piyushk** [comment]
No longer. You placed a comment in RedisListenerThread that explained it. I've opened #231 to deal with that issue.

**Comment by stonier** [comment]
Ok.
