### ISSUE TITLE
Failed registrations sneak into interfaces

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#239]
Failed registrations return None and these are anyway appended to flipped and pulled registration interfaces causing the following bug:

```
[INFO] [WallTime: 1387433002.047906] Scheduler : insufficient resources to satisfy request [957a5184-c767-4812-85b0-cd41de14a8a1]
[INFO] [WallTime: 1387433003.076720] Conductor: retrieving client information [dude]
[INFO] [WallTime: 1387433003.079982] Gateway : added pull rule [dude75da751e9bda4dc68c3f00bc4f8927a0:(/dude75da751e9bda4dc68c3f00bc4f8927a0/platform_info,service)]
[INFO] [WallTime: 1387433003.080597] Gateway : added pull rule [dude75da751e9bda4dc68c3f00bc4f8927a0:(/dude75da751e9bda4dc68c3f00bc4f8927a0/list_apps,service)]
[INFO] [WallTime: 1387433003.081059] Gateway : added pull rule [dude75da751e9bda4dc68c3f00bc4f8927a0:(/dude75da751e9bda4dc68c3f00bc4f8927a0/status,service)]
[INFO] [WallTime: 1387433003.081518] Gateway : added pull rule [dude75da751e9bda4dc68c3f00bc4f8927a0:(/dude75da751e9bda4dc68c3f00bc4f8927a0/invite,service)]
[INFO] [WallTime: 1387433003.122466] Conductor : new client found [dude]
[INFO] [WallTime: 1387433003.142484] Conductor : invited [dude][dude75da751e9bda4dc68c3f00bc4f8927a0]
[INFO] [WallTime: 1387433003.184020] Gateway : pulling in connection [service][/dude75da751e9bda4dc68c3f00bc4f8927a0/status][/app_manager][dude75da751e9bda4dc68c3f00bc4f8927a0]
[WARN] [WallTime: 1387433003.195391] Gateway : tried to register a service that is already locally available, aborting [/dude75da751e9bda4dc68c3f00bc4f8927a0/status]
Traceback (most recent call last):
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 70, in spin
    self._gateway.spin()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 76, in spin
    self.watcher_thread.start()
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 76, in start
    self._gateway.update_pulled_interface(connections, remote_gateway_hub_index)
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 194, in update_pulled_interface
    existing_registration = self.pulled_interface.find_registration_match(pull.gateway, pull.rule.name, pull.rule.node, pull.rule.type)
  File "/mnt/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/interactive_interface.py", line 269, in find_registration_match
    if (registration.remote_gateway == remote_gateway) and \
AttributeError: 'NoneType' object has no attribute 'remote_gateway'
[INFO] [WallTime: 1387433003.288117] Scheduler : new concert client [dude]
Compatibility Tree
```

**Comment by stonier** [comment]
Easy to fix, just handle the None for new_registration appends in gateway.py. But bigger concern is why it is happening in the concert.

**Comment by stonier** [comment]
Ach...don't start app managers inside the concert - that was the cause. I need to create big red flags when I am trying to do that.
