### ISSUE TITLE
Hub shutdown error

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#252]
This is wrapped up in the concert shutdown procedure...some failure in the shutdown logic.

Happens occasionally, but not all the time.

```
[ERROR] [WallTime: 1393988634.198750] Gateway : unknown error on shutdown [][<class 'httplib.CannotSendRequest'>]
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 618, in _handle_request
    response = convert_return_to_response(self.handler(request), self.response_class)
  File "/mnt/zaphod/code/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 206, in ros_service_shutdown
    self._shutdown()
  File "/mnt/zaphod/code/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 98, in _shutdown
    self._gateway.shutdown()
  File "/mnt/zaphod/code/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 82, in shutdown
    self.master.unregister(registration)
  File "/mnt/zaphod/code/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 387, in unregister
    self._unregister_subscriber(node_master, registration.connection.xmlrpc_uri, registration.connection.rule.name)
  File "/mnt/zaphod/code/ros/rocon/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 445, in _unregister_subscriber
    xmlrpcapi(xmlrpc_uri).publisherUpdate('/master', name, [])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest
[ERROR] [WallTime: 1393988634.200298] Error processing request: 
None
[ERROR] [WallTime: 1393988634.200715] failed to externally shut down gateway/hub [service [/concert/gateway/shutdown] responded with an error: error processing request: ]
```

**Comment by stonier** [comment]
77e871fb7ced52b19318927ed7586dd4693b8687
