### ISSUE TITLE
Master Error

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_multimaster#272]
```
[INFO] [WallTime: 1399887673.912328] Gateway : sending flip request [Cafed12e1fe4d440486d9d1cb2eec46bcfbe][subscriber][/whoola/cmd_vel][/mobile_base_nodelet_manager]
Traceback (most recent call last):
  File "/home/yujin/turtlebot/turtlebot/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/yujin/turtlebot/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 76, in spin
    self._gateway.spin()
  File "/home/yujin/turtlebot/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 78, in spin
    self.watcher_thread.start()
  File "/home/yujin/turtlebot/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 75, in start
    self._gateway.update_flipped_interface(connections, remote_gateway_hub_index)
  File "/home/yujin/turtlebot/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 154, in update_flipped_interface
    connections = self.master.generate_connection_details(flip.rule.type, flip.rule.name, flip.rule.node)
  File "/home/yujin/turtlebot/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 593, in generate_connection_details
    xmlrpc_uri = self.lookupNode(node)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 433, in lookupNode
    return self._succeed(self.handle.lookupNode(self.caller_id, node_name))        
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 154, in _succeed
    raise Error(msg)
rosgraph.masterapi.MasterError: unknown node [/whoola/camera_relay]
[whoola/camera/camera_nodelet_manager-30] killing on exit
[whoola/teleop_velocity_smoother-29] killing on exit
[ INFO] [1399887674.129741763]: Unloading nodelet /whoola/teleop_velocity_smoother from manager /mobile_base_nodelet_manager
```

**Comment by piyushk** [comment]
It looks like the node `/whoola/camera_relay` came up and was recorded, but then died before the master could add the flip. That's a pretty small window. We probably need to add better checks for successful registrations/lookups against the local master and behave appropriately when the connections fail.

**Comment by stonier** [comment]
Yeah, I think we have a couple of pretty small windows where we need to be retrying things.

**Comment by stonier** [comment]
Closing this - likely been covered by @asmodehn's large 2016 update, especially now that it works with the connection cache. Regardless, need more information to push forward on that.
