### ISSUE TITLE
error while starting rapp

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#289]
```
Traceback (most recent call last):
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 78, in spin
    self._gateway.spin()
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 78, in spin
    self.watcher_thread.start()
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 75, in start
    self._gateway.update_flipped_interface(connections, remote_gateway_hub_index)
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 154, in update_flipped_interface
    connections = self.master.generate_connection_details(flip.rule.type, flip.rule.name, flip.rule.node)
  File "/home/yujin/ros/turtlebot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 595, in generate_connection_details
    xmlrpc_uri = self.lookupNode(node)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 433, in lookupNode
    return self._succeed(self.handle.lookupNode(self.caller_id, node_name))        
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 154, in _succeed
    raise Error(msg)
rosgraph.masterapi.MasterError: unknown node [/adams/robot_pose_publisher]
```

**Comment by stonier** [comment]
Haven't seen for over a year. Reopen if it happens again.
