### ISSUE TITLE
error occurred while starting up solution

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#304]
I've never seen this before.

```
Traceback (most recent call last):
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 78, in spin
    self._gateway.spin()
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 78, in spin
    self.watcher_thread.start()
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 79, in start
    self._gateway.update_flipped_in_interface(registrations, remote_gateway_hub_index)
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 338, in update_flipped_in_interface
    new_registration = self.master.register(registration)
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 358, in register
    registration.connection.xmlrpc_uri)
  File "/home/piyushk/newrobot/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 524, in _register_subscriber
    xmlrpcapi(xmlrpc_uri).publisherUpdate('/master', name, pub_uri_list)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault -1: 'publisherUpdate: unknown method name'>
```

**Comment by stonier** [comment]
At a guess the subscriber is mid-constructing its xmlrpc server. i.e. socket connection was there, but the bits and pieces weren't.

This is not critical code though - here we are just being nice and telling the subscriber it should update its publisher list. Probably it hasn't got any publishers yet.

I added some error code to highlight the problem. For now we can ignore it, but if we see it again and it causes problems, reopen it.
