### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_multimaster#316]
```
Traceback (most recent call last):
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 81, in spin
    self._gateway.spin()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 78, in spin
    self.watcher_thread.start()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 75, in start
    self._gateway.update_flipped_interface(connections, remote_gateway_hub_index)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 132, in update_flipped_interface
    status = hub.get_flip_request_status(flip.remote_rule)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 748, in get_flip_request_status
    Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 62, in run
    self._hub_connection_lost_hook()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 179, in _hub_connection_lost_hook
    self._hub_connection_lost_gateway_hook(self)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 185, in _disengage_hub
    self._gateway.disengage_hub(hub)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 106, in disengage_hub
    self.hub_manager.disengage_hub(hub)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/hub_manager.py", line 244, in disengage_hub
    hub_to_be_disengaged.disconnect()  # necessary to kill failing socket receives
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_hub_client/src/rocon_hub_client/hub_client.py", line 142, in disconnect
    self._redis_server.connection_pool.disconnect()
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/connection.py", line 416, in disconnect
    for connection in all_conns:
RuntimeError: Set changed size during iteration

status = self.get_multiple_flip_request_status([remote_rule])
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 779, in get_multiple_flip_request_status
    rule_status, source, connection_list = utils.deserialize_request(flip)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/utils.py", line 225, in deserialize_request
    deserialized_list = deserialize(request_str)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/utils.py", line 185, in deserialize
    rospy.logwarn("Gateway : Error while deserialization[%s]"%e)
NameError: global name 'rospy' is not defined
```

**Comment by stonier** [comment]
More of an issue is why the data failed to deserialise, but as we don't have any output here, have to catch that next time.
