### ISSUE TITLE
Losing network while creating service

### ISSUE THREAD

**Issue by asmodehn** [robotics-in-concert/rocon_multimaster#338]
It seems gateway is not robust against that yet : 

```
[ERROR] [WallTime: 1458824651.636302] Gateway : error registering subscriber (is ROS_MASTER_URI and ROS_HOSTNAME or ROS_IP correctly set?)
[ERROR] [WallTime: 1458824651.636965] Gateway : errorcode [113] xmlrpc_uri [http://gocart204:35963/]
[INFO] [WallTime: 1458821627.314057] ConnectionCacheProxy: started inside node /concert/gateway
[INFO] [WallTime: 1458821627.314545]                     : with list topic at /concert/connection_cache/list
[INFO] [WallTime: 1458821627.314781]                     : and diff topic at /concert/connection_cache/diff
[INFO] [WallTime: 1458821627.356286] Gateway : checking if zeroconf services are available...
[INFO] [WallTime: 1458821627.868252] Gateway : discovered hub directly [http://localhost:6380]
[INFO] [WallTime: 1458821628.050811] Gateway : found existing mismatched public key on the hub, requesting resend for all flip-ins.
[INFO] [WallTime: 1458821628.051561] Gateway : registering on the hub [GoCart Concert]
[INFO] [WallTime: 1458821629.056585] Gateway : removing hub from the list to be resolved via zeroconf [already connected to this hub]
[INFO] [WallTime: 1458821655.496249] Gateway : received a flip request [gocart-server][publisher][/concert/clients/battery][/celeros]
[INFO] [WallTime: 1458821655.498745] Gateway : received a flip request [gocart-server][publisher][/concert/clients/heartbeat/beat][/gopher/heartbeat]
[INFO] [WallTime: 1458821655.500706] Gateway : received a flip request [gocart-server][publisher][/concert/clients/battery][/rocon/battery_interface]
[INFO] [WallTime: 1458821655.502402] Gateway : received a flip request [gocart-server][subscriber][/concert/clients/heartbeat/echo][/gopher/heartbeat]
[INFO] [WallTime: 1458821655.505124] Gateway : received a flip request [gocart-server][publisher][/concert/clients/gocart-server/platform_info][/rocon/app_manager]
[INFO] [WallTime: 1458821655.506684] Gateway : received a flip request [gocart-server][publisher][/concert/clients/gocart-server/name][/rocon/robot_identity]
[INFO] [WallTime: 1458821655.508623] Gateway : received a flip request [gocart-server][publisher][/concert/clients/gocart-server/battery][/rocon/battery_interface]
[INFO] [WallTime: 1458821655.513809] Gateway : received a flip request [gocart-server][publisher][/concert/clients/gocart-server/ssid][/rocon/robot_identity]
[INFO] [WallTime: 1458821655.515465] Gateway : received a flip request [gocart-server][publisher][/concert/clients/gocart-server/ip][/rocon/robot_identity]
[INFO] [WallTime: 1458821655.517366] Gateway : received a flip request [gocart-server][subscriber][/concert/clients/battery][/celeros]
[INFO] [WallTime: 1458821665.006441] Gateway : received a flip request [gocart-server][publisher][/concert/clients/gocart-server/battery][/celeros]
[INFO] [WallTime: 1458821665.008297] Gateway : received a flip request [gocart-server][subscriber][/concert/clients/gocart-server/battery][/celeros]
[INFO] [WallTime: 1458824648.619192] Gateway : received a flip request [gocart204][publisher][/concert/clients/battery][/celeros]
[INFO] [WallTime: 1458824648.621544] Gateway : received a flip request [gocart204][publisher][/concert/clients/gocart204/ip][/rocon/robot_identity]
[INFO] [WallTime: 1458824648.623515] Gateway : received a flip request [gocart204][subscriber][/concert/clients/battery][/celeros]
Traceback (most recent call last):
  File "/opt/groot/bootstrap_ws/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/opt/groot/bootstrap_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 81, in spin
    self._gateway.spin()
  File "/opt/groot/bootstrap_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 106, in spin
    self.update_flipped_in_interface(registrations, remote_gateway_hub_index)
  File "/opt/groot/bootstrap_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 373, in update_flipped_in_interface
    new_registration = self.master.register(registration)
  File "/opt/groot/bootstrap_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 105, in register
    registration.connection.xmlrpc_uri)
  File "/opt/groot/bootstrap_ws/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 272, in _register_subscriber
    xmlrpcapi(xmlrpc_uri).publisherUpdate('/master', name, pub_uri_list)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1301, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1448, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 113] No route to host
```

**Comment by stonier** [comment]
@asmodehn this get fixed?
