### ISSUE TITLE
masterapi may not be thread safe

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#74]
I have very occasionally gotten an error while running master.getSystemState -- mostly while running tests when things happen quite fast.

From this thread: http://bugs.python.org/issue6907, It look like httplib and xmlrpclib are not thread safe. Consequently, I believe rosgraph.Master() may not be thread safe. and rospy creates separate threads for everything...

I'll try to look into this issue in greater detail in a bit. I'll lock every call in masterapi and see if I can reproduce the error.

**Comment by piyushk** [comment]
I have attached the traceback. This has only appeared in rostests, where I guess the gateway is being stress tested a bit.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/piyushk/ros/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 40, in run
    connections = self.master.getConnectionState()
  File "/home/piyushk/ros/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 188, in getConnectionState
    publishers, subscribers, services = self.getSystemState()
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 483, in getSystemState
    return self._succeed(self.handle.getSystemState(self.caller_id))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 856, in putrequest
    raise CannotSendRequest()
CannotSendRequest
```

Relevant links:
- http://stackoverflow.com/questions/1925639/httplib-cannotsendrequest-error-in-wsgi
- http://bugs.python.org/issue6907

However, I just checked the masterapi code, and it does indeed lock around the getSystemState call internally. Consequently, I don't know what causes this error, but we should handle it gracefully -- i.e. something went wrong, lets not try to make updates based on this call.

**Comment by stonier** [comment]
Still a problem?

I wonder if we make getSystemState calls only in the watcher thread, will it resolve the problem?

**Comment by piyushk** [comment]
I think I forgot to close this one. getSystemState is now only called in the watcher thread ac63c4be28817a7a4baa4e62ec525d6826521fbc

I have also encapsulated the call to handle the error gracefully, and I don't think this error is produced anymore. Even if  it is, the next watcher update should be fine.
