### ISSUE TITLE
Remote gateway deserialization error

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#76]
remote_gateway_info works fine until a remote gateway has a public interface. Then I'm getting a serialisation error.

Calling it like so:

```
rosservice call /gateway/remote_gateway_info []
```

With error on the local gateway:

```

[INFO] [WallTime: 1349743357.500867] Gateway : connected to hub [gateway6][Pirate Hub].
Traceback (most recent call last):
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 615, in _handle_request
    response = convert_return_to_response(self.handler(request), self.response_class)
  File "/opt/multimaster/rocon_multimaster/multimaster_client/rocon_gateway/scripts/gateway.py", line 141, in rosServiceRemoteGatewayInfo
    public_interfaces = self.gateway_sync.hub.listPublicInterfaces(gateways)
  File "/opt/multimaster/rocon_multimaster/multimaster_client/rocon_gateway/src/rocon_gateway/hub_api.py", line 154, in listPublicInterfaces
    connection.deserialize(connection_str)
  File "/opt/multimaster/rocon_comms/gateway_comms/src/gateway_comms/msg/_Connection.py", line 206, in deserialize
    raise genpy.DeserializationError(e) #most likely buffer underfill
DeserializationError: unpack requires a string argument of length 4

```

**Comment by piyushk** [comment]
I'll test this out soon. Was planning on using it inside the advertise test, but haven't put everything together yet.
